export const mediaTypeOptions = [
    { value: "MOVIE", label: "Movie" },
    { value: "TV_SHOW", label: "TV Show" },
    { value: "MUSIC_ALBUM", label: "Music Album" },
    { value: "BOOK", label: "Book" },
];

export const formatOptions = [
    "VHS",
    "DVD",
    "Blu-ray",
    "Vinyl",
    "CD",
    "Cassette",
    "Hardcover",
    "Paperback",
    "Mass Market Paperback",
    "Digital",
];

export const genreOptions = [
    "ACTION",
    "ACTION_ADVENTURE",
    "ADVENTURE",
    "AFRICAN_MUSIC",
    "ALTERNATIVE",
    "ANIMATION",
    "ASIAN_MUSIC",
    "BIOGRAPHY",
    "BLUES",
    "BRAZILIAN_MUSIC",
    "BUSINESS",
    "CHRISTIAN",
    "CLASSICAL",
    "COMEDY",
    "COUNTRY",
    "CRIME",
    "CUMBIA",
    "DANCE",
    "DOCUMENTARY",
    "DRAMA",
    "EDUCATIONAL",
    "ELECTRONIC",
    "FAMILY",
    "FANTASY",
    "FOLK",
    "HISTORY",
    "HORROR",
    "INDIAN_MUSIC",
    "JAZZ",
    "KIDS",
    "LATIN_MUSIC",
    "METAL",
    "MYSTERY",
    "MUSIC",
    "NEWS",
    "POLITICS",
    "POP",
    "RAP_HIP_HOP",
    "REALITY",
    "REGGAE",
    "REGGAETON",
    "RELIGION",
    "R_AND_B",
    "ROCK",
    "ROMANCE",
    "SALSA",
    "SCIENCE_FICTION",
    "SCI_FI_FANTASY",
    "SOAP",
    "SOUL_FUNK",
    "SPORTS",
    "TALK",
    "THRILLER",
    "TV_MOVIE",
    "WAR",
    "WAR_POLITICS",
    "WESTERN",
    "YOUNG_ADULT",
    "OTHER",
];

export const statusOptions = [
    { value: "OWNED", label: "Owned" },
    { value: "WISHLISTED", label: "Wishlisted" },
];

export const mediaTypeFormatOptions = {
    MOVIE: [
        "VHS",
        "DVD",
        "Blu-ray",
        "Digital",
    ],

    TV_SHOW: [
        "VHS",
        "DVD",
        "Blu-ray",
        "Digital",
    ],

    MUSIC_ALBUM: [
        "Vinyl",
        "CD",
        "Cassette",
        "Digital",
    ],

    BOOK: [
        "Hardcover",
        "Paperback",
        "Mass Market Paperback",
        "Digital",
    ],
};

export const mediaTypeGenreOptions = {
    MOVIE: [
        "ACTION",
        "ACTION_ADVENTURE",
        "ADVENTURE",
        "ANIMATION",
        "COMEDY",
        "CRIME",
        "DOCUMENTARY",
        "DRAMA",
        "FAMILY",
        "FANTASY",
        "HISTORY",
        "HORROR",
        "MUSIC",
        "MYSTERY",
        "ROMANCE",
        "SCIENCE_FICTION",
        "SCI_FI_FANTASY",
        "THRILLER",
        "TV_MOVIE",
        "WAR",
        "WESTERN",
    ],

    TV_SHOW: [
        "ACTION_ADVENTURE",
        "ANIMATION",
        "COMEDY",
        "CRIME",
        "DOCUMENTARY",
        "DRAMA",
        "FAMILY",
        "FANTASY",
        "HISTORY",
        "HORROR",
        "KIDS",
        "MUSIC",
        "MYSTERY",
        "NEWS",
        "REALITY",
        "ROMANCE",
        "SCI_FI_FANTASY",
        "SOAP",
        "TALK",
        "THRILLER",
        "WAR_POLITICS",
    ],

    MUSIC_ALBUM: [
        "AFRICAN_MUSIC",
        "ALTERNATIVE",
        "ASIAN_MUSIC",
        "BLUES",
        "BRAZILIAN_MUSIC",
        "CHRISTIAN",
        "CLASSICAL",
        "COUNTRY",
        "CUMBIA",
        "DANCE",
        "ELECTRONIC",
        "FOLK",
        "INDIAN_MUSIC",
        "JAZZ",
        "KIDS",
        "LATIN_MUSIC",
        "METAL",
        "OTHER",
        "POP",
        "R_AND_B",
        "RAP_HIP_HOP",
        "REGGAE",
        "REGGAETON",
        "ROCK",
        "SALSA",
        "SOUL_FUNK",
    ],

    BOOK: [
        "ACTION_ADVENTURE",
        "ANIMATION",
        "COMEDY",
        "CRIME",
        "DOCUMENTARY",
        "DRAMA",
        "FAMILY",
        "FANTASY",
        "HISTORY",
        "HORROR",
        "KIDS",
        "MUSIC",
        "MYSTERY",
        "NEWS",
        "REALITY",
        "ROMANCE",
        "SCI_FI_FANTASY",
        "SOAP",
        "TALK",
        "THRILLER",
        "WAR_POLITICS",
        "OTHER",
    ],
};
